name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: cdk

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        fetch-depth: 0
    - name: Cache node modules (cdk)
      uses: actions/cache@v4
      with:
        path: cdk/node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('cdk/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - name: Debug workspace
      # run from the repo workspace root so we can see what's actually checked out
      working-directory: ${{ github.workspace }}
      run: |
        echo "GITHUB_WORKSPACE=$GITHUB_WORKSPACE"
        pwd
        ls -la "$GITHUB_WORKSPACE"
        echo '--- cdk dir ---'
        ls -la "$GITHUB_WORKSPACE/cdk" || true
        echo '--- cdk/html-website ---'
        ls -la "$GITHUB_WORKSPACE/cdk/html-website" || true
        echo '--- root package.json ---'
        cat "$GITHUB_WORKSPACE/package.json" || true
    - name: Install dependencies (cdk)
      run: npm ci
    - name: Run tests (cdk)
      run: npx jest --config jest.config.js --runInBand
